# Generated by Django 4.0.4 on 2022-05-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMangement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='typeProject',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectMangement.typeproject'),
        ),
    ]
